### PR TITLE
added http interface to hc run

### PR DESCRIPTION
**Pull request by zippy**
this just adds an env var so people can use the http interface with `hc run`

### CODE REVIEW

**Comment by zippy** [comment]
This is a good point about documentation.  Motivation is that I find them a very clean easy and expected way to get data into commands that lends itself to temporary settings via `export` and so on.

**Comment by zippy** [comment]
ok @Connoropolous , I got all the tests refactored and working, locally at least, we'll see what happens with CI.  But I will disable them again before merge because they still do take way too long.

**Comment by Connoropolous** [comment]
@zippy is this for after the release?

**Comment by zippy** [comment]
Yep not part of 0.0.3.  I just pushed turning off that run test, because it takes too long for travis.  You can turn it on and test locally if you like.  Otherwise please re-review so we can merge using http in hc.

**Pull request merged**
