### PR TITLE
Added test for bridging to demonstrate double serialization issue #1360

### PR DESCRIPTION
**Pull request by juliolrmonteiro**
## PR summary

This adds a test to app_spec to investigate issue #1360, at the same time being the first test to ever use the new scenario API bridging capabilities.

The new test currently doesn't pass due to the potential double serialization bug.

Please help me investigate.

Cheers,
Julio

## testing/benchmarking notes

( if any manual testing or benchmarking was/should be done, add notes and/or screenshots here )

## followups

( any new tickets/concerns that were discovered or created during this work but aren't in scope for review here )

## changelog

Please check one of the following, relating to the [CHANGELOG](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG.md)

- [ ] this is a code change that effects some consumer (e.g. zome developers) of holochain core so there is an 'Unreleased' CHANGELOG item, with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [ ] this is not a code change, or doesn't effect anyone outside holochain core development

### CODE REVIEW

**Comment by Connoropolous** [comment]
I don't know if I can fix this, but I can maybe help debug...

First, I will drop in here where the failed error in the CI appears:

```
2019-04-30 15:16:12 ThreadId(1451):alice: debug/dna: '********DEBUG******** BRIDGING RAW response from test-bridge JsonString("\"{\\\"Ok\\\":{\\\"App\\\":[\\\"post\\\",\\\"{\\\\\\\"content\\\\\\\":\\\\\\\"Holo world\\\\\\\",\\\\\\\"date_created\\\\\\\":\\\\\\\"now\\\\\\\"}\\\"]}}\"")'
BRIDGE CALL RESULT: {"Err":{"Internal":"unknown variant `{\"Ok\":{\"App\":[\"post\",\"{\\\"content\\\":\\\"Holo world\\\",\\\"date_created\\\":\\\"now\\\"}\"]}}`, expected one of `App`, `Dna`, `AgentId`, `Deletion`, `LinkAdd`, `LinkRemove`, `LinkList`, `ChainHeader`, `ChainMigrate`, `CapToken`, `CapTokenGrant` at line 1 column 105"}}
Stopping instance "alice"...
Stopping instance "bob"...
not ok 159 TypeError: Cannot read property 'App' of undefined
  ---
    operator: fail
    at: Test.Scenario._tape (/root/project/nodejs_conductor/index.js:191:23)
    stack: |-
      Error: TypeError: Cannot read property 'App' of undefined
          at Test.assert [as _assert] (/root/project/app_spec/test/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/root/project/app_spec/test/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/root/project/app_spec/test/node_modules/tape/lib/test.js:319:10)
          at Test.bound [as fail] (/root/project/app_spec/test/node_modules/tape/lib/test.js:77:32)
          at Test.Scenario._tape (/root/project/nodejs_conductor/index.js:191:23)
          at <anonymous>
```

**Comment by juliolrmonteiro** [comment]
Hey there,
I am trying to run the tests with the latest hc binary (installing using `hc-cli-install`, even removed my `.cargo` folder), and it seems many tests are failing with undefined and `Argument deserialization failed` errors, maybe because of some structural changes, like:

```
2019-05-01 22:46:19 ThreadId(982):alice: err/zome: invoke_commit_app_entry failed to deserialize Entry: JsonString("{\"entry\":{\"App\":[\"post\",\"{\\\"content\\\":\\\"Holo world...3\\\",\\\"date_created\\\":\\\"now\\\"}\"]},\"options\":{\"provenance\":[]}}")
```
``` 
1..125
# tests 125
# pass  62
# fail  63
```

**Comment by lucksus** [comment]
Yeah, I agree @zippy. I would also love to get @thedavidmeister's eyes on this. I was already thinking we might want to add `TryFrom` implementations for the `Result` specializations I was using here to `JsonString` - or approach this problem on a more general level if adequate. Also, so far we are not forcing zome functions to return results, but most of the ones we have in app-spec do.. This could also have been solved by doing this deserializing of the result manually in the calling zome code. But then we would definitely need more `TryFrom` implementations.. So ultimately, this is a question convenience. 

I will revisit this today with a bit more time. Just wanted to get @juliolrmonteiro unblocked yesterday quickly.

**Comment by thedavidmeister** [comment]
@lucksus yes, previously it was not possible but @willemolding did some work recently that means we could enforce this at the type level i believe :)

**Pull request merged**
