### PR TITLE
add uuid option to admin/dna/install_from_file

### PR DESCRIPTION
**Pull request by maackle**
## PR summary

TODO:

- [x] write a test

## changelog

Please check one of the following, relating to the [CHANGELOG-UNRELEASED.md](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG-UNRELEASED.md)

- [x] this is a code change that effects some consumer (e.g. zome developers) of holochain core so it is added to the CHANGELOG-UNRELEASED.md (linked above), with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [ ] this is not a code change, or doesn't effect anyone outside holochain core development

### CODE REVIEW

**Comment by zippy** [comment]
I'm not sure I understand the motivation for this PR.  How does the UUID "overrride" what's in the DNA, does it re-write the DNA?  That would change the hash.  Is that the point?

**Comment by maackle** [comment]
@zippy yes, it changes the hash, which is the main motivation. It's similar to setting a property on the DNA through the admin interface, which we already have an admin interface method for. It's needed for [Diorama](https://github.com/holochain/diorama) (the new scenario test harness) to ensure that each test runs in an independent network with a different DNA hash. I didn't want to alter `properties` because the DNA actually cares about its properties, so a test harness shouldn't be injecting randomness into a semantically relevant chunk of data. UUID seems like the vehicle for making uniquely hashed copies of the same DNA.

**Comment by Connoropolous** [comment]
@maackle I think you included this work in your other PR? We can close?

**Comment by lucksus** [comment]
Why WIP? This looks good, can we merge if tests pass?

**Comment by maackle** [comment]
I know I neglected this branch but my intention was to review this separately and merge it in.

**Pull request merged**
