### PR TITLE
appveyor hosted

### PR DESCRIPTION
**Pull request by thedavidmeister**
- [x] I have added a summary of my changes to the changelog

## changes

- [x] move everything from travis to av that Just Works
- [x] precompile everything on av with aws ami
- [x] make sure av only runs one build on the pr
- [x] move slow dry run build on travis to develop branch only

AV = 7 min windows wall time (longest test is conductor)

## followup

- move all pr builds from travis to av
- move all builds from travis to circle/av
- downgrade travis to 5 builds
- decide on build times vs. cost for av
- get @AshantiMutinta access to the remote desktop for the master instance to look around

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@philipbeadle yes, because we have no standard installation process for windows (we never have) we have no idea why something would(n't) fail

travis obviously ships a bunch of things in their image, and individuals working locally must have started with more deps preinstalled than we have, or figured it out themselves

e.g. some of the builds that i couldn't ship to AV included missing openssl :/

@duffybelfield is working on getting a windows friendly install script (we use it to build the AMI this is based on) and that will improve as we bring the tests back online

**Comment by thedavidmeister** [comment]
the other approach could be to leave EAV back in and move that whole suite back to travis until we can figure out the issue, i'm happy either way

my main reason for doing it the way that i did is because the build at https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/23356009 looks like a legit fail, in that _some_ people running windows probably will see this fail - it doesn't look like a missing lib or something to me, just a regular old flaky test

**Comment by zippy** [comment]
> my main reason for doing it the way that i did is because the build at https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/23356009 looks like a legit fail, in that _some_ people running windows probably will see this fail - it doesn't look like a missing lib or something to me, just a regular old flaky test

Yah that does look like a legit failure.  @AshantiMutinta any idea what's going on here?

**Comment by thedavidmeister** [comment]
@zippy just spoke to @AshantiMutinta and we will do a followup where she can have direct access to the instance on AWS and see what's causing the problems

we suspect it might actually be permissions on the temp file system or something

**Pull request merged**
