### PR TITLE
MDBOOK: show status in chapter outline

### PR DESCRIPTION
**Pull request by Connoropolous**
I want people to know right away about the status of the book, when they come upon it

I also want them to know, at a glance, which articles to look into and which to ignore

### CODE REVIEW

**Comment by emalinus** [comment]
Just "E" or complete? Might we also use an "IP" for in progress too?

**Comment by Connoropolous** [comment]
@emalinus yeah, could be good to have another status option too... 

how might we qualify 'in progress'? and I'd recommend just (I) since space in the table of contents is precious

**Comment by emalinus** [comment]
We could just say "'I' indicates that an article is in progress." I was gonna re-word some of the welcome stuff anyway, so I can make the change

**Comment by Connoropolous** [comment]
The only hesitation I have about an (I) for in progress is that even the
"complete" articles are very much a work in progress so I would worry it'd
be meaningless, or make ones that didn't have an I claim to be "complete".

**Comment by emalinus** [comment]
Ah, good point. Let's just leave it as you suggested, then, and trust that folks will be understanding of our progress :)

**Pull request merged**
