### PR TITLE
linux install script: update apt cache as root [fix]

### PR DESCRIPTION
**Pull request by hoijui**
APT cache is stored system globally,
and thus in a place where only root has access to,
so updating it requires root access.

Please check one of the following, relating to the [CHANGELOG](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG.md), which should be updated if relevant
- [ ] my changes to the code affect some exposed aspect of the developer experience, and I have added an item to relevant 'Added, Fixed, Changed, Removed, Deprecated, or Security' heading under the 'Unreleased' heading of the CHANGELOG, with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [x] my changes to the code do not affect any exposed aspect of the developer experience

### CODE REVIEW

**Comment by thedavidmeister** [comment]
this works on all the cold builds currently, so sudo isn't required there at least (likely because CI uses root)

adding sudo to the `npm install` previously seems to have broken our deployment scripts (still investigating this)

can we demonstrate a failing case showing sudo is needed here?

**Comment by hoijui** [comment]
I also think it is run as root on CI, so `as_root=""` (It would break with `sudo`).
on my local debian, running the script as non root, without this commit, I get:

> …/holochain-rust $ ./scripts/install/auto.sh
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
[sudo] password for user:

**Comment by lazaridiscom** [comment]
Works on my side when applying patch.

Confirming logic.

**Comment by thedavidmeister** [comment]
ok, we'll let's ship this and see how it impacts `0.0.11` :)

**Comment by Connoropolous** [comment]
@thedavidmeister is this still relevant?

**Comment by hoijui** [comment]
yes, it should still be merged.
as said, wihtout this, install on linux will fail when run by non-root.

**Comment by Connoropolous** [comment]
Thanks @hoijui . 

There is however, a slightly broader framing for the question, which involves a lot of other work that @thedavidmeister has been doing on the installation process, that I am wondering whether it actually does away with the necessity for this whole script.

**Comment by hoijui** [comment]
ok. But even if it will be deleted soon, I can't see how it could make more sense to delete a broken script then to delete a working one. In the worst case, he wil lget a merge conflict when merging in his changes, and then has to decide to delete this fie anyway.

**Comment by thedavidmeister** [comment]
i have merged, if cold builds break i will rollback as we have a release scheduled soon

**Pull request merged**
