### PR TITLE
remove newrelic from holochain

### PR DESCRIPTION
**Pull request by zippy**
## PR summary

Removes new-relic building completely from conductor for now.

## testing/benchmarking notes

( if any manual testing or benchmarking was/should be done, add notes and/or screenshots here )

## followups

( any new tickets/concerns that were discovered or created during this work but aren't in scope for review here )

## changelog

- [ ] if this is a code change that effects some consumer (e.g. zome developers) of holochain core,  then it has been added to [our between-release changelog](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG-UNRELEASED.md) with the format 

```markdown
- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)
```

## documentation

- [ ] this code has been documented according to our [docs checklist](https://hackmd.io/@freesig/Hk9AmKJNS)

### CODE REVIEW

**Comment by Connoropolous** [comment]
what was newrelic there for, and why take it out?

**Comment by zippy** [comment]
> what was newrelic there for, and why take it out?

We added it for debugging purposes to try and track down some cross-process problems with the tracing it offeres, however it's causing problems in our holoport build chain so we need to clean it out for now.  In the "production" context rewrelic doesn't make any sense for holochain at all because it's centralized monitoring.  It may make sense to add back into sim2h_server which is a centralized service so that it can be monitored.

**Comment by freesig** [comment]
This will need to be removed from holochain tracing aswell.
Let's just put it the deps under a conditional compile and make the new relic a pass through so you don't need to comment all these out

**Comment by zippy** [comment]
obsolete

**Pull request closed without merging**
