### PR TITLE
All performance

### PR DESCRIPTION
**Pull request by lucksus**
## PR summary

This is the combination of #1915, #1916, #1917, #1920 (and thus #1923). Each of these focuses on a particular performance issue which is easier to review separate from the rest, but all together are intended to mitigate the problems @freesig found in his profiling runs.

## testing/benchmarking notes

( if any manual testing or benchmarking was/should be done, add notes and/or screenshots here )

## followups

( any new tickets/concerns that were discovered or created during this work but aren't in scope for review here )

## changelog

- [ ] if this is a code change that effects some consumer (e.g. zome developers) of holochain core,  then it has been added to [our between-release changelog](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG-UNRELEASED.md) with the format 

```markdown
- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)
```

## documentation

- [ ] this code has been documented according to our [docs checklist](https://hackmd.io/@freesig/Hk9AmKJNS)

### CODE REVIEW

**Comment by freesig** [comment]
Overall cpu use. The peak at the mid - end is when I'm spamming commits on passthrough.
image
Still spawning lots of threads but they seem to be moving faster:
image
I'll profile with basic chat now

**Comment by freesig** [comment]
This is the hottest paths now:
```
2.22 s   27.6%	0 s	 	               holochain_core::context::Context::spawn_task::h8d8d9a41da8959eb
2.22 s   27.6%	0 s	 	                futures_executor::thread_pool::ThreadPool::run::h7842753946a64b35
2.22 s   27.6%	0 s	 	                 futures_executor::local_pool::LocalPool::run_until::hbba5dd2e4dff1dda
2.22 s   27.5%	0 s	 	                  std::thread::local::LocalKey$LT$T$GT$::with::hb772bd0002b41cb5
2.20 s   27.4%	0 s	 	                   futures_executor::local_pool::LocalPool::run_until::_$u7b$$u7b$closure$u7d$$u7d$::h950dcb2e6ffcfb33
2.16 s   26.8%	8.00 ms	 	                    _$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h671842b9b1669892
2.12 s   26.3%	4.00 ms	 	                     holochain_core::workflows::run_holding_workflow::_$u7b$$u7b$closure$u7d$$u7d$::h005ef1f7682b188c
2.12 s   26.3%	4.00 ms	 	                      std::future::poll_with_tls_context::h805a22ffd8491dc5
1.17 s   14.5%	0 s	 	                       std::future::poll_with_tls_context::ha8f38387e4598d63
1.17 s   14.5%	0 s	 	                        _$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::_$u7b$$u7b$closure$u7d$$u7d$::h417de5c709735f23
1.17 s   14.5%	0 s	 	                         holochain_core::nucleus::validation::validate_entry::_$u7b$$u7b$closure$u7d$$u7d$::hec82dd9a20f0aeb4
1.13 s   14.0%	0 s	 	                          std::future::poll_with_tls_context::_$u7b$$u7b$closure$u7d$$u7d$::h68dc19a53e71c719
1.13 s   14.0%	0 s	 	                           _$LT$std..future..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h15314fc00cb14e61
1.12 s   13.9%	2.00 ms	 	                            holochain_core::nucleus::ribosome::run_dna::run_dna::hc16a646f7827d537
510.00 ms    6.3%	0 s	 	                             wasmi::module::ModuleInstance::invoke_export::h8073119f4409c277
457.00 ms    5.6%	0 s	 	                             holochain_core::nucleus::ribosome::factories::wasm_instance_factory::h092fa6e5b65362dc
149.00 ms    1.8%	0 s	 	                             core::ptr::real_drop_in_place::hcf24e1e9ff961bc4

```

**Comment by freesig** [comment]
This is basic chat all cpu:
image
Some big peaks but it feels a lot more responsive. 
This PR is a big improvement compared to yesterday. I'll try basic chat with to machines and see what I find

**Comment by lucksus** [comment]
Closing as all commits are merged to develop through other PRs now.

**Pull request closed without merging**
