### PR TITLE
MDBOOK: intro to building apps and intro to DNA

### PR DESCRIPTION
**Pull request by Connoropolous**
This is the beginning of a proposed "Building Apps" structure roughly of the form seen in this workflowy
https://workflowy.com/s/EzcM.WxqP4uJqte

### CODE REVIEW

**Comment by Connoropolous** [comment]
Hi folks. Per my discussions with Emaline and David Meister, we are going to work on increasing the pace of documentation throughput, with a focus on content development now and QA reviews and detailed passes over the whole book later in the process. 
So highest priority for reviews is for factual correctness. According to that, I'm going to merge, but please feel free to make other suggested edits as review comments on this PR, or just make the updates to the merged version yourself and submit.

**Comment by thedavidmeister** [comment]
@Connoropolous could we use a tag like "rough cut" or "draft" or something to indicate which content should be pushed through?

or is the idea that all content now should be pushed through?

**Comment by Connoropolous** [comment]
I think that still operating from a case-by-case basis is better...

Within this section, there will be a LOT of articles I think, and they are ideally each fairly small, not too complex, and cover something very specific. I had an idea to post them up as PRs through small logical chunks, but all in all I am wanting to do this "section" very quickly as a draft. Get something up, get something in there... 

There will be enough work that is guaranteed for us to have to do in this section once the decisions which are in discussion right now are made and implemented. So I want to try to cover what I assess we've actually landed on, and leave out stuff that's still being determined

**Comment by thedavidmeister** [comment]
@Connoropolous what you're facing isn't that different from the code situation tbh

we're slowly finding our way re: Messy Improvement vs. Perfect Deliverable

**Pull request merged**
