### PR TITLE
[WIP] Update first_steps for the 0.0.20-alpha3 release

### PR DESCRIPTION
**Pull request by jamesray1**
Adds some fixes to update for the 0.0.17-alpha2 release and also some minor proofreading.

Ignore my below comments.

The full terminal session going through this is at https://pastebin.com/7W7wCJv3 and https://pastebin.com/N1xwUFTx, with the end of the latter showing the failure of `hc test`:

```zsh
$ hc test
Packaging files for testing to file: "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
    Finished release [optimized] target(s) in 0.09s
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
    Finished release [optimized] target(s) in 0.09s
Created DNA package file at "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
DNA hash: QmS2FN9ctXQbV7qKkTr4paBJveytPPos8PqQTFxELSjz6R
Installing node_modules
> npm install --silent
[@holochain/holochain-nodejs] Success: "/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/bin-package/index.node" is installed via remote
added 156 packages from 111 contributors and audited 264 packages in 18.691s
found 0 vulnerabilities

Running tests in test/index.js
> node test/index.js
TAP version 13
# description of example test
Reading DNA from ./dist/holochain-rust-todo.dna.json
Failed to load instance alice from storage: ErrorGeneric("State could not be loaded due to NoneError")
Initializing new chain...
Starting instance "alice"...
Exception occurred while calling zome function:  unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
Stopping instance "alice"...
not ok 1 unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
  ---
    operator: fail
    at: Test.Scenario._tape (/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/index.js:195:23)
    stack: |-
      Error: unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
          at Test.assert [as _assert] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:319:10)
          at Test.bound [as fail] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:77:32)
          at Test.Scenario._tape (/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/index.js:195:23)
          at <anonymous>
          at runMicrotasksCallback (internal/process/next_tick.js:122:5)
          at _combinedTickCallback (internal/process/next_tick.js:132:7)
          at process._tickCallback (internal/process/next_tick.js:181:9)
  ...

1..1
# tests 1
# pass  0
# fail  1

Error: command node test/index.js was not successful
```

## PR summary
Update first_steps tutorial to 0.0.17-alpha2.

## followups

( any new tickets/concerns that were discovered or created during this work but aren't in scope for review here )

Fix the error.

## changelog

Please check one of the following, relating to the [CHANGELOG-UNRELEASED.md](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG-UNRELEASED.md)

- [ ] this is a code change that effects some consumer (e.g. zome developers) of holochain core so it is added to the CHANGELOG-UNRELEASED.md (linked above), with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [x] this is not a code change, or doesn't effect anyone outside holochain core development

### CODE REVIEW

**Comment by jamesray1** [comment]
Although you can see it above just to be clearer the first error is

> Failed to load instance alice from storage: ErrorGeneric("State could not be loaded due to NoneError")


If anyone wants to explain how this error can be fixed and provide more detail on the cause, go ahead!

```zsh
 13:20:37  ✘  jr@fm  ~/holochain-rust-todo  ⬡ v8.16.0  21s 
$ RUST_BACKTRACE=1 hc test
Packaging files for testing to file: "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
    Finished release [optimized] target(s) in 0.08s
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
    Finished release [optimized] target(s) in 0.08s
Created DNA package file at "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
DNA hash: QmS2FN9ctXQbV7qKkTr4paBJveytPPos8PqQTFxELSjz6R
Running tests in test/index.js
> node test/index.js
TAP version 13
# description of example test
Reading DNA from ./dist/holochain-rust-todo.dna.json
Failed to load instance alice from storage: ErrorGeneric("State could not be loaded due to NoneError")
Initializing new chain...
Starting instance "alice"...
Exception occurred while calling zome function:  unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
Stopping instance "alice"...
not ok 1 unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
  ---
    operator: fail
    at: Test.Scenario._tape (/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/index.js:195:23)
    stack: |-
      Error: unable to call zome "my_zome" function "create_my_entry": InternalFailure(Dna(ZomeNotFound("Zome \'my_zome\' not found")))
          at Test.assert [as _assert] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:319:10)
          at Test.bound [as fail] (/home/jr/holochain-rust-todo/test/node_modules/tape/lib/test.js:77:32)
          at Test.Scenario._tape (/home/jr/holochain-rust-todo/test/node_modules/@holochain/holochain-nodejs/index.js:195:23)
          at <anonymous>
          at runMicrotasksCallback (internal/process/next_tick.js:122:5)
          at _combinedTickCallback (internal/process/next_tick.js:132:7)
          at process._tickCallback (internal/process/next_tick.js:181:9)
  ...

1..1
# tests 1
# pass  0
# fail  1

Error: command node test/index.js was not successful

 19:04:53  ✘  jr@fm  ~/holochain-rust-todo  ⬡ v8.16.0 
$ 
```

**Comment by jamesray1** [comment]
See also https://github.com/jamesray1/holochain-rust-todo for the current state of the repo.

**Comment by jamesray1** [comment]
The error occurs in line 165 here:

https://github.com/holochain/holochain-rust/blob/7dd59d5e3235bbee8c9ae42ea951e24c68607104/conductor_api/src/holochain.rs#L160-L174

**Comment by jamesray1** [comment]
So this is a new computer and I had actually forgotten to install the Rust extension. :man_facepalming: I now am getting:

```zsh
 10:56:32  jr@fm  ~/holochain-rust-todo  ⬡ v8.16.0   master ✘ ⬆ ✹ ✭ 
$ hc test
Packaging files for testing to file: "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
   Compiling lists v0.1.0 (/home/jr/holochain-rust-todo/zomes/lists/code)
error[E0061]: this function takes 4 parameters but 3 parameters were supplied
   --> src/lib.rs:118:2
    |
118 |     hdk::link_entries(&list_addr, &item_addr, "items")?; // if successful, link to list address
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 4 parameters

error[E0061]: this function takes 3 parameters but 2 parameters were supplied
   --> src/lib.rs:129:22
    |
129 |     let list_items = hdk::get_links(&list_addr, "items")?.addresses()
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0061`.
error: Could not compile `lists`.

To learn more, run the command again with --verbose.
Error: command cargo build --release --target=wasm32-unknown-unknown --target-dir=target was not successful

 10:57:15  ✘  jr@fm  ~/holochain-rust-todo  ⬡ v8.16.0   master ✘ ⬆ ✹ ✭ 
$ 
```

**Comment by jamesray1** [comment]
Failing build:
```
     Running /root/nix-holochain/target/release/deps/holochain_test_bin-e47613f7b7240545

running 3 tests
Error occured in p2p network module, on receive: ErrorMessage { msg: "(memory-auto-puid-1-0) No sender channel found for DNA_A::alex" }

stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved::ha29e0499d7bd464f (0x55cdad3396cd)
   1: failure::backtrace::internal::InternalBacktrace::new::hb3b73ba275b7e8f4 (0x55cdad338fad)
   2: failure::backtrace::Backtrace::new::h0d2d13470f2af96f (0x55cdad338c1b)
   3: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h9f3c0e1fbeb3833a (0x55cdad04456d)
   4: <failure::error::Error as core::convert::From<F>>::from::hd8384c54aff24875 (0x55cdad046b7d)
   5: failure::error_message::err_msg::h7515899ee25dca10 (0x55cdad0443dc)
   6: holochain_net::in_memory::memory_server::InMemoryServer::priv_send_one_with_cell_id::h1ff8cf6401139421 (0x55cdad03a7fe)
   7: holochain_net::in_memory::memory_server::InMemoryServer::priv_send_one::hb819b7715dd73b8f (0x55cdad03a919)
   8: holochain_net::in_memory::memory_server::InMemoryServer::priv_check_or_fail::h5e3aa09658227fb3 (0x55cdad03a37a)
   9: holochain_net::in_memory::memory_server::InMemoryServer::serve::h32ee929c35867cd4 (0x55cdad037150)
  10: <holochain_net::in_memory::memory_worker::InMemoryWorker as holochain_net::connection::net_connection::NetWorker>::receive::hf169d2d75c1f06cc (0x55cdad01ba57)
  11: std::sys_common::backtrace::__rust_begin_short_backtrace::hde4bb9ae23c30546 (0x55cdad03dcf9)
  12: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h64b2dea0723e4bb7 (0x55cdad032c8b)
  13: std::panicking::try::do_call::h317a5a66398d81b4 (0x55cdad03d647)
  14: __rust_maybe_catch_panic (0x55cdad3694d9)
             at src/libpanic_unwind/lib.rs:92
  15: std::panicking::try::h73c7a72936d32ced (0x55cdad03d5fd)
  16: std::panic::catch_unwind::hc52ceade325544cd (0x55cdad032cbb)
  17: <F as alloc::boxed::FnBox<A>>::call_box::h68e418266fc95126 (0x55cdad02026e)
  18: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h93cf98f22e0fd5c9 (0x55cdad3688bd)
             at /rustc/19f8958f827e379be9b0ffc93fca580ec8ffac77/src/liballoc/boxed.rs:744
      std::sys_common::thread::start_thread::he849c686b0bafe63
             at src/libstd/sys_common/thread.rs:14
      std::sys::unix::thread::Thread::new::thread_start::hccbef199b5f9a0dc
             at src/libstd/sys/unix/thread.rs:81
  19: start_thread (0x7fbf044f45a6)
  20: __GI___clone (0x7fbf0401522e)
  21: <unknown> (0x0)
Error occured in p2p network module, on receive: ErrorMessage { msg: "(memory-auto-puid-1-2) No sender channel found for DNA_A::alex" }

stack backtrace:
   0: backtrace::capture::Backtrace::new_unresolved::ha29e0499d7bd464f (0x55cdad3396cd)
   1: failure::backtrace::internal::InternalBacktrace::new::hb3b73ba275b7e8f4 (0x55cdad338fad)
   2: failure::backtrace::Backtrace::new::h0d2d13470f2af96f (0x55cdad338c1b)
   3: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h9f3c0e1fbeb3833a (0x55cdad04456d)
   4: <failure::error::Error as core::convert::From<F>>::from::hd8384c54aff24875 (0x55cdad046b7d)
   5: failure::error_message::err_msg::h7515899ee25dca10 (0x55cdad0443dc)
   6: holochain_net::in_memory::memory_server::InMemoryServer::priv_send_one_with_cell_id::h1ff8cf6401139421 (0x55cdad03a7fe)
   7: holochain_net::in_memory::memory_server::InMemoryServer::priv_send_one::hb819b7715dd73b8f (0x55cdad03a919)
   8: holochain_net::in_memory::memory_server::InMemoryServer::priv_check_or_fail::h5e3aa09658227fb3 (0x55cdad03a37a)
   9: holochain_net::in_memory::memory_server::InMemoryServer::serve::h32ee929c35867cd4 (0x55cdad037150)
  10: <holochain_net::in_memory::memory_worker::InMemoryWorker as holochain_net::connection::net_connection::NetWorker>::receive::hf169d2d75c1f06cc (0x55cdad01ba57)
  11: std::sys_common::backtrace::__rust_begin_short_backtrace::hde4bb9ae23c30546 (0x55cdad03dcf9)
  12: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h64b2dea0723e4bb7 (0x55cdad032c8b)
  13: std::panicking::try::do_call::h317a5a66398d81b4 (0x55cdad03d647)
  14: __rust_maybe_catch_panic (0x55cdad3694d9)
             at src/libpanic_unwind/lib.rs:92
  15: std::panicking::try::h73c7a72936d32ced (0x55cdad03d5fd)
  16: std::panic::catch_unwind::hc52ceade325544cd (0x55cdad032cbb)
  17: <F as alloc::boxed::FnBox<A>>::call_box::h68e418266fc95126 (0x55cdad02026e)
  18: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h93cf98f22e0fd5c9 (0x55cdad3688bd)
             at /rustc/19f8958f827e379be9b0ffc93fca580ec8ffac77/src/liballoc/boxed.rs:744
      std::sys_common::thread::start_thread::he849c686b0bafe63
             at src/libstd/sys_common/thread.rs:14
      std::sys::unix::thread::Thread::new::thread_start::hccbef199b5f9a0dc
             at src/libstd/sys/unix/thread.rs:81
  19: start_thread (0x7fbf044f45a6)
  20: __GI___clone (0x7fbf0401522e)
  21: <unknown> (0x0)
test tests::run_two_nodes_basic_tests_with_in_memory_network ... ok
test tests::run_three_nodes_tests_with_in_memory_network ... FAILED
test tests::run_two_nodes_list_tests_with_in_memory_network ... ok

failures:

---- tests::run_three_nodes_tests_with_in_memory_network stdout ----
TestNode.track_dna(): Json(JsonString("{\"method\":\"trackDna\",\"dnaAddress\":\"DNA_A\",\"agentId\":\"alex\"}"))
self connected result 1: PeerConnected(PeerData { agent_id: "alex" })
TestNode.track_dna(): Json(JsonString("{\"method\":\"trackDna\",\"dnaAddress\":\"DNA_A\",\"agentId\":\"billy\"}"))
self connected result 2: PeerConnected(PeerData { agent_id: "billy" })
TestNode.track_dna(): Json(JsonString("{\"method\":\"trackDna\",\"dnaAddress\":\"DNA_A\",\"agentId\":\"camille\"}"))
self connected result 2: PeerConnected(PeerData { agent_id: "camille" })
thread 'tests::run_three_nodes_tests_with_in_memory_network' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:209
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: <core::option::Option<T>>::unwrap
  10: holochain_test_bin::three_workflows::hold_and_publish_test
  11: holochain_test_bin::launch_three_nodes_test_with_memory_network
  12: holochain_test_bin::tests::run_three_nodes_tests_with_in_memory_network
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1475
             at /rustc/19f8958f827e379be9b0ffc93fca580ec8ffac77/src/libcore/ops/function.rs:231
             at /rustc/19f8958f827e379be9b0ffc93fca580ec8ffac77/src/liballoc/boxed.rs:734
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/19f8958f827e379be9b0ffc93fca580ec8ffac77/src/libstd/panicking.rs:276
             at /rustc/19f8958f827e379be9b0ffc93fca580ec8ffac77/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1430


failures:
    tests::run_three_nodes_tests_with_in_memory_network

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p holochain_test_bin --bin holochain_test_bin'
Exited with code 101
```

**Comment by zippy** [comment]
Thanks @jamesray1.  Looks like there's some slippage in our release process re updating version number.  

:point_right:  @thedavidmeister 

I think the build process wouldn't fail if you updated to latest develop as the three node test should have been fixed.  Can you confirm?

**Comment by zippy** [comment]
I've fixed a bunch of different version errors over in:  I've fixed a bunch of other missed version numbers in #1482 

@jamesray1 would you be willing to modify this PR to just be the other substantive fixes that don't have anything to do with the version numbers, becaus 0.0.17 is already out of date...

**Comment by jamesray1** [comment]
"What I'll do is I'll update to the latest release and check that the tutorial works fine."—
https://github.com/holochain/holochain-rust/pull/1482/files#r290990549

Then update the tutorial with the latest release.

**Comment by jamesray1** [comment]
OK it looks like I'll need to update the tutorial again:
```
 11:21:39  jr@fm  ~/holochain-rust-todo  ⬡ v8.16.0   master ✔ 
$ hc test
Packaging files for testing to file: "/home/jr/holochain-rust-todo/dist/holochain-rust-todo.dna.json"
> cargo build --release --target=wasm32-unknown-unknown
   Compiling lists v0.1.3 (/home/jr/holochain-rust-todo/zomes/lists/code)
error: no rules expected the token `link_type`
  --> src/lib.rs:35:21
   |
35 |                     link_type: "items",
   |                     ^^^^^^^^^ no rules expected this token in macro call

error[E0061]: this function takes 3 parameters but 4 parameters were supplied
   --> src/lib.rs:118:2
    |
118 |     hdk::link_entries(&list_addr, &item_addr, "items", "")?; // if successful, link to list address
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error[E0061]: this function takes 2 parameters but 3 parameters were supplied
   --> src/lib.rs:129:22
    |
129 |     let list_items = hdk::get_links(&list_addr, Some("items".to_string()), None)?.addresses()
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0061`.
error: Could not compile `lists`.

To learn more, run the command again with --verbose.
Error: command cargo build --release --target=wasm32-unknown-unknown was not successful

 11:21:46  ✘  jr@fm  ~/holochain-rust-todo  ⬡ v8.16.0   master ✔ 
$ 
```

**Comment by jamesray1** [comment]
Note that I am having issues with using nix as detailed in holochain/holochain-rust#1538, so I'll still wait to be able to install and run the nix-shell without issues before seeing if the latest release works. Again, the other changes are minor, so they can wait, rather than cherry-picking commits or manually editing.

**Comment by jamesray1** [comment]
Being worked on at https://hackmd.io/cvdB9Ag6R5utXWJfQPFdWg.

**Pull request closed without merging**
