### PR TITLE
net sleep techdebt

### PR DESCRIPTION
**Pull request by Connoropolous**
- [ ] I have added a summary of my changes to the changelog
no because its just a comment

### CODE REVIEW

**Comment by Connoropolous** [comment]
@ddd-mtl and @zippy any thoughts on how to actually make this TODO that I'm adding go away?

**Comment by ddd-mtl** [comment]
@Connoropolous Its already in the tree:
https://realtimeboard.com/app/board/o9J_kyiXmFs=/?moveToWidget=3074457346457995629

**Comment by Connoropolous** [comment]
Ok cool. I wasn't sure, and in doing a whole bunch of code review recently came across this and made .a note to myself to check in about it. 

Would you prefer I close the PR, merge the PR, or leave the PR open for further implementation work on this?

**Comment by ddd-mtl** [comment]
@Connoropolous I'd add a TODO saying its a hack until Core takes in account the 'P2pReady' message sent by the network module

**Comment by Connoropolous** [comment]
@ddd-mtl updated the comment, and with a link to the RTB item, can you approve?

**Pull request merged**
