### PR TITLE
Reenable code coverage

### PR DESCRIPTION
**Pull request by zippy**
I have just re-enabled code coverage, time to get things back above 85%!

### CODE REVIEW

**Comment by zippy** [comment]
You're kidding!  To get code coverage passing we have to agree to a different formatting!?!?

**Comment by lucksus** [comment]
Updated the nightly version. Don't know why, but that usually results in a different rustfmt output.. that is why we pinned it in the first place, right?

**Comment by lucksus** [comment]
But that update to nightly, rebuilding tarpaulin for version 0.6.9 is what fixed it.
Updating futures to 0.3.0-alpha10 and changing the fmt are collateral.

**Comment by zippy** [comment]
I'm ok us bringing the tools version to the same version as the core version right now, knowing that going forward we can still bump the core version WITHOUT bumping the tools version.

**Pull request merged**
