### PR TITLE
Small adjustment

### PR DESCRIPTION
**Pull request by sphinxc0re**
- [ ] I have added a summary of my changes to the changelog

### CODE REVIEW

**Comment by sphinxc0re** [comment]
@Connoropolous That change might be especially interesting for you.

**Comment by Connoropolous** [comment]
That is so interesting! I was trying that and it wasn’t working for me, and I can’t see how what I had tried is different than what you wrote. 

I was getting getting EnvVar::Something is not a module

**Comment by pjkundert** [comment]
It cleans up the problem for me, too.  I did delete all my Cargo.lock files before trying it, though -- I don't know if that had an effect.  Is serde_json no longer a (separate) crate that needs to be included, then?  Perhaps we should clean up everywhere else then, too...

**Comment by lucksus** [comment]
`hc_dkpi` is an `edition = 2018` crate. In Edition 2018 you don't need to declare `extern crate ..`, you can just use it directly. @pjkundert

**Pull request merged**
