### PR TITLE
reversed in-memory representation and iterator of SourceChain

### LINKED ISSUE #35: use a collection that allows more efficient inserting of pairs into source chains
currently we insert new pairs at the start of a vector, which is O(n)

other collection types can do O(1) or O(log n) for inserts

https://doc.rust-lang.org/std/collections/#sequences

### PR DESCRIPTION
**Pull request by Slavoj**
This seems to me to be the more natural form. 

Side effect:
resolves #35

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@Slavoj we're deliberately iterating from top to bottom

from memory, this is how it works in the go version we're porting from, and follows the direction of headers referencing the hashes of previous items in the chain, so is a natural "next" in this sense (you can start at any pair and move to the next pair by looking up the hash #30)

i'd suggest that if we believe it makes sense to support chronological iteration, that we provide iterators for both directions

**Comment by thedavidmeister** [comment]
although, admittedly, it's pretty confusing that the pair calls the "next" pair from iteration the "previous" hash :P

**Comment by Slavoj** [comment]
@thedavidmeister not confusing at all and I understand the reasoning for the iteration in this direction. Makes totally sense.

I just was curious about the code and looked for the issues as an exercise. For issue #35 I could not imagine a better collection other than appending a Pair to Vec (O(1)) and instead of changing the collection, revert the iterator direction to satisfy the old behaviour. But given the existing `rev` method of `Iterator` and my missing insight in your architecture I felt better with skipping the implementation work for the new iterators :-)

I am looking forward to the new rust holochain implementation. Keep up the good work!

**Comment by thedavidmeister** [comment]
@Slavoj ah, well, for example we could do a hashmap with `O(1)~*` for inserts and `O(1)~` for `get` by hash and a single "top" pair, which can then be iterated from... but then we lose efficient `nth` lookup by index...

in fact, the go version has several parallel internal representations of the same data!

https://github.com/holochain/holochain-proto/blob/develop/chain.go#L52

```go
type Chain struct {
	Hashes   []Hash
	Headers  []*Header
	Entries  []Entry
	TypeTops map[string]int // pointer to index of top of a given type
	Hmap     map[Hash]int   // map header hashes to index number
	Emap     map[Hash]int   // map entry hashes to index number
```

that approach gives high theoretical performance but then also higher complexity (bugs) and is coupled to a specific implementation...

the plan moving forward (i've discussed this with @zippy ) is to focus on a simple, implementation independent API for working with a source chain. We can always layer performance optimisations (e.g. caches and indexes) on top of that for specific implementations (e.g. file system, databases, etc.) _after_ we have some evidence that there is a problem somewhere.

actually i'd love a hand with things @Slavoj if you're interested i've put together a simple roadmap for the `chain.go` port:

https://github.com/holochain/holochain-rust/issues/29

**Comment by Slavoj** [comment]
@thedavidmeister I am happy to help, but can not commit too much time or rust experience. So my first priority would be to not slow you down.

But if you create a simple roadmap anyway or if you maybe put some TODOs in the code when the trait/API grows, I will try to follow the development and come back to you if I see a chance to help.

**Pull request closed without merging**
