### PR TITLE
holochain_net: JsonProtocol doc update

### PR DESCRIPTION
**Pull request by ddd-mtl**
Please check one of the following, relating to the [CHANGELOG](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG.md), which should be updated if relevant
- [ ] my changes to the code affect some exposed aspect of the developer experience, and I have added an item to relevant 'Added, Fixed, Changed, Removed, Deprecated, or Security' heading under the 'Unreleased' heading of the CHANGELOG, with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [x] my changes to the code do not affect any exposed aspect of the developer experience

### CODE REVIEW

**Comment by Connoropolous** [comment]
happy about this :) why's it WIP?

**Comment by zippy** [comment]
@ddd-mtl is this something we can merge soon?  We are doing PR cleanup, and we realized that we haven't reviewed this because it was labeled "WIP".  What should be the next step?

**Comment by ddd-mtl** [comment]
@zippy Yes, this is mergeable or closable. It was WIP because I thought I would get back to it to add more comments, but I forgot about this PR, and will probably focus on the updated protocol in lib3h.

**Comment by thedavidmeister** [comment]
i'm going to merge, i don't think we need mutiple reviews for minor docs here

**Pull request merged**
