### PR TITLE
Revert: PickleDB auto-dump

### PR DESCRIPTION
**Pull request by lucksus**
This reverts commit 80d529d5752acc38966b35d2e3597330d67aa43c.

Please check one of the following, relating to the [CHANGELOG](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG.md), which should be updated if relevant
- [ ] my changes to the code affect some exposed aspect of the developer experience, and I have added an item to relevant 'Added, Fixed, Changed, Removed, Deprecated, or Security' heading under the 'Unreleased' heading of the CHANGELOG, with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [x] my changes to the code do not affect any exposed aspect of the developer experience

# PickleDB auto-dump is super expensive
... at least for us since we have DNAs in our source chains that are several MBs of size. With auto-dump turned on every change triggers a complete rewrite of the DB which includes writing several MBs. That happens synchronously in the thread that triggers the change, rendering every action several orders of magnitude slower. Biggest candle in the FlameGraph now is dumping:
Screenshot from 2019-04-10 13-11-51

### CODE REVIEW

**Comment by zippy** [comment]
Why did app-spec fail?

**Comment by zippy** [comment]
I'm happy to approve this as a temporary step, but we need to talk about how to force persistance before a commit entry call returns.

**Comment by thedavidmeister** [comment]
"a complete rewrite of the db" is giving me bad vibes, is this because of something we did or pickledb?

i would not expect that rewriting a new top to my chain triggers a write of the whole (immutable) chain!

**Comment by lucksus** [comment]
@thedavidmeisterl, it's pickleDB: https://docs.rs/pickledb/0.3.0/pickledb/#dumping-data-to-a-file

**Comment by AshantiMutinta** [comment]
It was done like this for Crash safe purposes https://www.reddit.com/r/rust/comments/agumun/check_out_pickledb_a_lightweight_and_simple/

**Comment by thedavidmeister** [comment]
@lucksus @AshantiMutinta does sqlite avoid this?

**Pull request merged**
