### PR TITLE
Fixing proc-macro paths

### PR DESCRIPTION
**Pull request by AshantiMutinta**
## PR summary
Fixing proc macros paths that were missed in the moving of the branch
## testing/benchmarking notes

( if any manual testing or benchmarking was/should be done, add notes and/or screenshots here )

## followups

( any new tickets/concerns that were discovered or created during this work but aren't in scope for review here )

## changelog

Please check one of the following, relating to the [CHANGELOG-UNRELEASED.md](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG-UNRELEASED.md)

- [ ] this is a code change that effects some consumer (e.g. zome developers) of holochain core so it is added to the CHANGELOG-UNRELEASED.md (linked above), with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [x] this is not a code change, or doesn't effect anyone outside holochain core development

### CODE REVIEW

**Comment by Connoropolous** [comment]
I'm assuming you found this because of issue #1737?

**Comment by AshantiMutinta** [comment]
> 
> 
> I'm assuming you found this because of issue #1737?

yes i did :)

**Comment by Connoropolous** [comment]
Cool was hoping you'd see it!

**Comment by Connoropolous** [comment]
I agree it would seem to mean that. ?

**Comment by AshantiMutinta** [comment]
> 
> 
> Oh, so this means app_spec_proc_macro is not tested anymore on CI?



> 
> 
> I agree it would seem to mean that. ?

There was a time it was explicitly disabled because of app_spec problems

**Pull request merged**
