### PR TITLE
Remove two unused core_types

### PR DESCRIPTION
**Pull request by Connoropolous**
its not used anywhere in the codebase. It used to be, obviously :p 

found this during my rustdoc work

### CODE REVIEW

**Comment by zippy** [comment]
I think this got superceeded by @AshantiMutinta work on "EAV attributes define and validate allowed characters for attribute names see #576"  is that correct?

**Comment by AshantiMutinta** [comment]
> 
> 
> I think this got superceeded by @AshantiMutinta work on "EAV attributes define and validate allowed characters for attribute names see #576" is that correct?

Hes this is true, validation is now done at the eav level

**Comment by Connoropolous** [comment]
So can y’all approve this? :)

**Comment by thedavidmeister** [comment]
i'm happy to see the old agent cruft cleaned up

merge when green :+1:

**Comment by Connoropolous** [comment]
thanks David

**Pull request merged**
