### PR TITLE
Linux install script: do not install `sudo` [fix] #980

### PR DESCRIPTION
**Pull request by hoijui**
Without `sudo` available, and without being run as root,
we can not install `sudo`,
so previous code was bogus.

Also, a script for installing a software should not
by itsself install `sudo`,
which by some is considered a security risk.

Now it uses `sudo` if available, and otherwise requires to be run by root.

Please check one of the following, relating to the [CHANGELOG](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG.md), which should be updated if relevant
- [ ] my changes to the code affect some exposed aspect of the developer experience, and I have added an item to relevant 'Added, Fixed, Changed, Removed, Deprecated, or Security' heading under the 'Unreleased' heading of the CHANGELOG, with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [x] my changes to the code do not affect any exposed aspect of the developer experience

### CODE REVIEW

**Comment by lazaridiscom** [comment]
not tested, but code looks very clean.

Confirming the logic.

**Comment by thedavidmeister** [comment]
this breaks all the cold builds on CI - https://circleci.com/gh/holochain/holochain-rust/15741

**Comment by thedavidmeister** [comment]
i think the issue is that circle uses pipefail, so `which sudo > /dev/null` silently kills builds...

**Comment by thedavidmeister** [comment]
```
root@621e9dde120d:~/project# . ./scripts/install/auto.sh 
bash: sudo: command not found
This script requires  or root priviledges
Connection to 34.224.100.93 closed.
```

for some reason this doesn't show up in the GUI but is visible when i ssh in manually

**Comment by thedavidmeister** [comment]
ok i think we're good now, it was two things, fixes pushed to develop for tomorrow's release:

- root user id _is_ equal to `0` so `-eq` not `-ne`
- debian needs an `apt-get update` before attempting to install `curl` and `git`

**Pull request merged**
