### PR TITLE
Sim2h Gossip Refetch

### PR DESCRIPTION
**Pull request by lucksus**
## PR summary

Currently, sim2h only requests gossip lists from nodes (i.e. the list of hashes a node is holding) only once - right after the node connected. If that node is missing something, sim2h picks a random other node to get that missing data from, to then delegate it back to the incomplete node.

So far, this process was quite fragile and might contribute for a good portion of the issues we encounter in the wild: if anything goes wrong (like that random node not having those entries neither, or a connection failure), there is nothing that would fix that. This node will never got to hold those missing entries, unless it reconnects again. Which is also what matches our experience of real-world tests.

These changes improve the handling of missing data at nodes.
We now cache data about which node is missing what. And then we periodically check-in with that node, re-request it's gossip list and trigger the gossip process again, if something is still missing

## testing/benchmarking notes

( if any manual testing or benchmarking was/should be done, add notes and/or screenshots here )

## followups

( any new tickets/concerns that were discovered or created during this work but aren't in scope for review here )

## changelog

- [x] if this is a code change that effects some consumer (e.g. zome developers) of holochain core,  then it has been added to [our between-release changelog](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG-UNRELEASED.md) with the format 

```markdown
- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)
```

## documentation

- [ ] this code has been documented according to our [docs checklist](https://hackmd.io/@freesig/Hk9AmKJNS)

### CODE REVIEW

**Comment by Connoropolous** [comment]
this sounds fantastic @lucksus ... I've been finding in my own testing that something along these lines has definitely been occurring, during real world tests I've done so far.

**Comment by Connoropolous** [comment]
I wonder if, in order to test this type of functionality, you would actually need to mock unreliable/intermittently connected nodes?

**Comment by lucksus** [comment]
@Connoropolous, I'm afraid this doesn't fix (at least all) of these problems. Tried yesterday with @zippy and I could see how this code gets exercised - but we could confirm that @zippy's node got entry data that is then later missing in its gossip list. So there seems to be a problem in core, which we believe is related to this issue: https://github.com/holochain/holochain-rust/issues/1824

But yeah, this change is still something that will catch many other problems, so we should get it in :)

**Comment by lucksus** [comment]
Regarding flaking network testing: yes!
We are also working on setting up test scenarios with many nodes and real Internet between them.

But programmatically creating package and connection drops in tests would be a really good thing. Is there a tool you could recommend?

**Comment by lucksus** [comment]
There might have been discussion around the name `arc_radius` somewhere here, @maackle: https://github.com/holochain/lib3h/pull/487.

Otherwise, mentioning @neonphog for a potential clarification :)

**Pull request merged**
