### PR TITLE
spike: use CAS in HashTable

### PR DESCRIPTION
**Pull request by thedavidmeister**
followups:

- #398 combine address and key
- #399 reuse path safety logic from `FileTable`
- #400 use the filesystem for instances

### CODE REVIEW

**Comment by ddd-mtl** [comment]
Wondering if we still need FileTable and MemoryTable? Can't we just do:HashTable<CAS

**Comment by thedavidmeister** [comment]
@ddd-mtl yeah man, that makes sense to me, actually i'm more worried about the serialization/deserialization of entries atm

will make a branch to isolate my concerns re: type handling

**Comment by ddd-mtl** [comment]
@thedavidmeister yeah ok, makes sense. 👍

**Comment by thedavidmeister** [comment]
hash table is gone

**Pull request closed without merging**
