### PR TITLE
CI Travis windows

### PR DESCRIPTION
**Pull request by ddd-mtl**
Compiles but does not launch tests as wabt requires python which we can't install for windows when there are secrets in the travis repo settings.

### CODE REVIEW

**Comment by sphinxc0re** [comment]
Okay, it seems like you can't install these via `choco`. But you can install them via the official installers (http://zeromq.org/distro:microsoft-windows)

**Comment by sphinxc0re** [comment]
There is one repo that lets you install zmq via `choco`: https://github.com/keenbrowne/chocolatey-zeromq

**Comment by ddd-mtl** [comment]
@sphinxc0re How do I tell travis to install that chocolatey package?

**Comment by ddd-mtl** [comment]
It won't work because its v4.0.4. We need at least v4.1

**Comment by sphinxc0re** [comment]
@ddd-mtl `choco` is installed automatically. You just have to use it. `choco install ...`

**Comment by zippy** [comment]
Doing an admin merge to get this working, despite the code-coverage and binaries issue.  The former we need to address, but is not specific to this pull request as it happend after JsonString.  The latter we will handle as a follow-up when we have more staffing to handle DevOps.

**Pull request merged**
