### PR TITLE
WIP: circle ci scaffold test

### PR DESCRIPTION
**Pull request by Connoropolous**
## testing/benchmarking notes

( if any manual testing or benchmarking was/should be done, add notes and/or screenshots here )

## followups

( any new tickets/concerns that were discovered or created during this work but aren't in scope for review here )

## changelog

Please check one of the following, relating to the [CHANGELOG](https://github.com/holochain/holochain-rust/blob/develop/CHANGELOG.md)

- [ ] this is a code change that effects some consumer (e.g. zome developers) of holochain core so there is an 'Unreleased' CHANGELOG item, with the format `- summary of change [PR#1234](https://github.com/holochain/holochain-rust/pull/1234)`
- [ ] this is not a code change, or doesn't effect anyone outside holochain core development

### CODE REVIEW

**Comment by Connoropolous** [comment]
@thedavidmeister any advice on how to solve the `hc command not found` issue?

**Comment by thedavidmeister** [comment]
@Connoropolous yeah, `~/.cargo/bin` is not _necessarily_ on the user's path (in this case it is not)

this could be fixed by vendoring bins into the repo, or otherwise changing the install scripts

i think the hack/workaround here is to re-export the path to include the built binaries, i'll put a fix up

**Comment by thedavidmeister** [comment]
@Connoropolous ok i got your greens

saw this:

```
With Rust already installed switch to it by running the following commands:
$ rustup toolchain install nightly-2019-01-24
$ rustup default nightly-2019-01-24
```

that's gonna need to stop recommending `rustup` in a followup (e.g. for the reason you discovered)

**Comment by thedavidmeister** [comment]
@Connoropolous for reference - https://github.com/NixOS/nix/issues/971

but we should be using the official holochain docker that has nix user issues resolved :thinking:

**Comment by thedavidmeister** [comment]
imma poke around in ssh

**Comment by thedavidmeister** [comment]
@Connoropolous kk i got it running green

i also added a mac option too but it's too slow to run on every PR, if you're into it we can shift it to develop only

there is this output also, but it doesn't fail builds

```
Failed to load instance alice from storage: ErrorGeneric("State could not be loaded due to NoneError")
```

**Comment by Connoropolous** [comment]
Good stuff @thedavidmeister !

There's one more thing before this PR is ready to merge though actually, we need to use `npm link` to connect the built version of the holochain-nodejs to the initialized app

**Comment by Connoropolous** [comment]
Oh, and @thedavidmeister this is intentional... you're not the only one to mistake this for an "error?"

> Failed to load instance alice from storage: ErrorGeneric("State could not be loaded due to NoneError")

I tried many times to improve this messaging, but it still looks like some kind of error. It just means its initializing a chain for the first time, not rebooting it

**Comment by Connoropolous** [comment]
I don't know exactly how to implement this, but here's the criteria:

`npm link` needs to be run within `nodejs_conductor` folder

`npm link @holochain/holochain-nodejs` needs to be run within the `test` folder of an `hc init`ed app

**Comment by thedavidmeister** [comment]
@Connoropolous right, so it must be trying to do something resulty with the init state, which is wrong probably but nothing to do with this

i'll look at the link

**Comment by Connoropolous** [comment]
@maackle this PR would be a good place for us to update the scaffolding code to Diorama based, since this would also introduce ongoing CI testing for it

**Comment by Connoropolous** [comment]
and @thedavidmeister we can also be coming back to this, and working with it as part of the moving of nodejs_conductor to a different repo

**Comment by Connoropolous** [comment]
@thedavidmeister I am blocked on knowing how I would update this... my blocker is:

I don't know to edit holonix to add the command that we'd added here, and do some kind of local development on it?

**Pull request closed without merging**
