### PR TITLE
add and use execute permissions on install scripts

### PR DESCRIPTION
**Pull request by nmaro**
- [X] I have added a summary of my changes to the changelog

### CODE REVIEW

**Comment by nmaro** [comment]
@thedavidmeister I looked for all occurrences of `sudo` in the code and it looks fine.

**Comment by zippy** [comment]
So @thedavidmeister remember when you asked why there were different build scripts for the release build?  In part it was because of this issue, that sudo didn't exist on the travis CI boxes and I had to install it first with a non-sudo `apt-get install`, so I couldn't even have it in the script.   I know we want to merge those scripts, but that's something to take into account in that merge.

**Comment by thedavidmeister** [comment]
@zippy there's no harm in running `apt-get install -y sudo` again if it's already installed, should just detect the existing install and move on

@nmaro i was hoping that we add something to the README that says "do NOT use sudo when running the script" - because ubuntu would now have sudo and mac breaks when you use sudo

**Comment by thedavidmeister** [comment]
aight, i had a bit of a play with this locally

```sh
docker run --rm -it -v `pwd`:/holochain:ro ubuntu bash
cd /holochain
./scripts/install/auto.sh
```

gives:

```
/holochain/scripts/install/ubuntu.sh: line 4: sudo: command not found
/holochain/scripts/install/ubuntu.sh: line 5: sudo: command not found
/holochain/scripts/install/ubuntu.sh: line 8: sudo: command not found
/holochain/scripts/install/ubuntu.sh: line 14: sudo: command not found
/holochain/scripts/install/ubuntu.sh: line 17: curl: command not found
/holochain/scripts/install/ubuntu.sh: line 17: sudo: command not found
/holochain/scripts/install/ubuntu.sh: line 18: sudo: command not found
/holochain/scripts/install/ubuntu.sh: line 19: curl: command not found
/holochain/scripts/install/ubuntu.sh: line 20: sudo: command not found
/holochain/scripts/install/ubuntu.sh: line 21: npm: command not found
```

so yay, the script runs, but less yay on the sudo deps

hopefully can be fixed by starting the script with an `apt-get install sudo`

CI should have all failed like my docker did :thinking: so it must still be doing `. ./...` instead of `./...`

**Comment by thedavidmeister** [comment]
i pushed a few tweaks

wait for `0.0.6-alpha` to land and be merged into develop, then pull develop, resolve conflicts then test again :)

**Comment by thedavidmeister** [comment]
release 0.0.6 tracking here btw - https://github.com/holochain/holochain-rust/pull/1108

**Comment by thedavidmeister** [comment]
updated this in light of #1192

**Comment by thedavidmeister** [comment]
the `sudo npm install` is a bad idea, that is a mistake i believe

https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

**Comment by thedavidmeister** [comment]
yup, sudo npm probably did this https://travis-ci.com/holochain/holochain-rust/jobs/190252618

**Pull request merged**
